version: '3'
services:
  app:
    build: ./docker/httpd
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql

  mysql:
    build: ./docker/mysql
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=db_test
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
